/**
 * Menu WhatsApp par défaut Sojori — aligné srv-admin/defaultChatbotMenu.ts
 * Utilisé pour initialiser le template Admin global (listing_owner_config_templates).
 */
export const SOJORI_DEFAULT_MENU_OPTIONS = [
  {
    code: 'A',
    label: 'Menu principal 📋',
    enabled: true,
    availability: { type: 'always' },
    action: 'show_main_menu',
    createsTask: false,
  },
  {
    code: 'D',
    label: '🕐 Gestion Arrivée & Départ',
    enabled: true,
    availability: { type: 'always' },
    action: 'show_submenu_d',
    createsTask: false,
  },
  {
    code: 'D1',
    label: 'Choisir heure arrivée ⬇️',
    enabled: true,
    availability: {
      type: 'time_window',
      from: { unit: 'days', value: 7, reference: 'before_checkin' },
      to: { unit: 'days', value: 1, reference: 'before_checkin' },
    },
    action: 'select_arrival_time',
    createsTask: true,
    taskType: 'arrival_reception',
    taskSchedule: 'selected_time',
  },
  {
    code: 'D2',
    label: 'Choisir heure départ ⬆️',
    enabled: true,
    availability: {
      type: 'time_window',
      from: { unit: 'days', value: 7, reference: 'before_checkin' },
      to: { unit: 'hours', value: 12, reference: 'before_checkout' },
    },
    action: 'select_departure_time',
    createsTask: true,
    taskType: 'departure_checkout',
    taskSchedule: 'selected_time',
  },
  {
    code: 'D3',
    label: 'Déclarer heure arrivée 📍',
    enabled: false,
    availability: {
      type: 'time_window',
      from: { unit: 'days', value: 3, reference: 'before_checkin' },
      to: { unit: 'hours', value: 2, reference: 'before_checkin' },
    },
    action: 'declare_arrival_time',
    createsTask: false,
  },
  {
    code: 'D4',
    label: 'Déclarer heure départ 📍',
    enabled: false,
    availability: {
      type: 'time_window',
      from: { unit: 'days', value: 1, reference: 'on_checkin_day' },
      to: { unit: 'hours', value: 2, reference: 'before_checkout' },
    },
    action: 'declare_departure_time',
    createsTask: false,
  },
  {
    code: 'J',
    label: '🎯 Services Conciergerie',
    enabled: true,
    availability: { type: 'always' },
    action: 'show_submenu_j',
    createsTask: false,
  },
  {
    code: 'J1',
    label: 'Transport 🚗',
    enabled: true,
    availability: { type: 'always' },
    action: 'request_transport',
    createsTask: true,
    taskType: 'transport_service',
    taskSchedule: 'selected_time',
    serviceConfig: { source: 'listing_services', category: 'transportServices' },
  },
  {
    code: 'J2',
    label: 'Courses 🛒',
    enabled: true,
    availability: { type: 'always' },
    action: 'request_shopping',
    createsTask: true,
    taskType: 'shopping_service',
    taskSchedule: 'selected_time',
    serviceConfig: { source: 'listing_services', category: 'shoppingServices' },
  },
  {
    code: 'J3',
    label: 'Personnalisé 🎯',
    enabled: true,
    availability: { type: 'always' },
    action: 'request_custom_service',
    createsTask: true,
    taskType: 'custom_service',
    taskSchedule: 'selected_time',
    serviceConfig: { source: 'listing_services', category: 'customServices' },
  },
  {
    code: 'B',
    label: 'Réservation 📅 & Langue 🌍',
    enabled: true,
    availability: { type: 'always' },
    action: 'change_language',
    createsTask: false,
  },
  {
    code: 'C',
    label: 'Parcours Arrivée/Départ 🚶‍♂️',
    enabled: true,
    availability: { type: 'after_booking_confirmed' },
    action: 'show_reservation_details',
    createsTask: false,
  },
  {
    code: 'E',
    label: 'Enregistrement voyageurs 👥',
    enabled: true,
    availability: {
      type: 'time_window',
      from: { unit: 'days', value: 3, reference: 'before_checkin' },
      to: { unit: 'days', value: 0, reference: 'on_checkin_day' },
    },
    action: 'guest_registration',
    createsTask: false,
  },
  {
    code: 'F',
    label: 'Accès & codes 🔐',
    enabled: true,
    availability: {
      type: 'conditional_and_time',
      requires: 'E_completed,D1_completed',
      from: { unit: 'days', value: 7, reference: 'before_checkin' },
      to: { unit: 'days', value: 1, reference: 'after_checkout' },
    },
    action: 'show_access_info',
    dataSource: 'listing_access',
    createsTask: false,
  },
  {
    code: 'G',
    label: 'Propriété & WiFi 🏠',
    enabled: true,
    availability: { type: 'always' },
    action: 'show_property_info',
    createsTask: false,
  },
  {
    code: 'H',
    label: 'Règles & à propos 📋',
    enabled: true,
    availability: { type: 'always' },
    action: 'show_house_rules',
    createsTask: false,
  },
  {
    code: 'I',
    label: 'Demande ménage 🧹',
    enabled: true,
    availability: {
      type: 'time_window',
      from: { unit: 'days', value: 7, reference: 'before_checkin' },
      to: { unit: 'hours', value: 12, reference: 'before_checkout' },
    },
    action: 'request_cleaning_service',
    createsTask: true,
    taskType: 'on_demand_cleaning',
    taskSchedule: 'selected_time',
    serviceConfig: { source: 'listing_services', serviceType: 'cleaningServices' },
  },
  {
    code: 'K',
    label: 'Support 🆘',
    enabled: true,
    availability: { type: 'always' },
    action: 'contact_support',
    createsTask: false,
  },
  {
    code: 'L',
    label: 'Service client 💌',
    enabled: true,
    availability: { type: 'always' },
    action: 'contact_service_client',
    createsTask: false,
  },
];

export function cloneSojoriDefaultMenuOptions() {
  return JSON.parse(JSON.stringify(SOJORI_DEFAULT_MENU_OPTIONS));
}
