// Garder synchronisé avec apps/srv-sockets/src/sockets/SocketEvents.ts (sojori-production)
export const SOCKET_EVENTS = {
  JOIN_ROOM: 'JOIN_ROOM',
  MINUT_NEW_EVENT: 'MINUT_NEW_EVENT',
  CONVERSATION_CHANGED: 'CONVERSATION_CHANGED',
  NEW_SENDED_MSG: 'NEW_SENDED_MSG',
  NEW_RECIVED_MSG: 'NEW_RECIVED_MSG',
  READ_MSG: 'READ_MSG',
  MODIFIED_MSG: 'MODIFIED_MSG',
  NEW_RESERVATION: 'NEW_RESERVATION',
  UPDATE_RESERVATION: 'UPDATE_RESERVATION',
  NEW_TASK: 'NEW_TASK',
  UPDATE_TASK: 'UPDATE_TASK',
} as const;

export const DEFAULT_ROOMS = {
  ADMIN: 'ADMIN',
  RESERVATION_ADMIN_ROOM: 'RESERVATION_ADMIN_ROOM',
  TASK_ADMIN_ROOM: 'TASK_ADMIN_ROOM',
  MINUT: 'MINUT',
  CHAT: 'CHAT',
  RU_CHAT: 'RU_CHAT',
  CHANNEXMESSAGE: 'CHANNEXMESSAGE',
} as const;
