/**
 * Mappings utilisés par les listings / import-sync RU — à migrer dans l’orchestrator (section Annonces).
 * Données principalement en base srv-listing (+ srv-channels pour champs XML RU).
 */

import type { MappingGroup } from './mappingTypes';

export const LISTING_RU_MAPPING_GROUPS: MappingGroup[] = [
  {
    id: 'amenities',
    label: 'Amenities',
    description: 'Catalogue RU, mapping Sojori et catégories UI listing.',
    items: [
      {
        id: 'amenities-catalog',
        label: 'Catalogue amenities',
        description: 'Amenities synchronisées depuis RU (rentalAmenityId).',
        path: '/admin/Listing/amenityConfig',
        target: 'legacy',
        legacyTabHint: 'Onglet Amenities',
        tags: ['RU', 'Sojori'],
        apiHint: 'amenities',
        database: 'srv-listing',
      },
      {
        id: 'amenities-mapping',
        label: 'Mapping amenities RU → Sojori',
        description: 'Ordre et lien ID RU → document Amenity (import RU).',
        path: '/admin/Listing/amenityConfig',
        target: 'legacy',
        legacyTabHint: 'Onglet Amenities Mapping',
        tags: ['RU', 'import'],
        apiHint: 'amenitiesmapping · resolve-ru-amenities',
        database: 'srv-listing',
      },
      {
        id: 'amenities-categories',
        label: 'Catégories amenities',
        description: 'Regroupement UI des amenities sur le formulaire listing.',
        path: '/admin/Listing/amenityConfig',
        target: 'legacy',
        legacyTabHint: 'Onglet Categories',
        tags: ['Sojori', 'UI'],
        apiHint: 'amenitiesincategoriesmapping',
        database: 'srv-listing',
      },
    ],
  },
  {
    id: 'images',
    label: 'Photos & types d’images',
    description: 'Types RU, catalogue Sojori et ordre (import photos RU).',
    items: [
      {
        id: 'image-types-sojori',
        label: 'Types images Sojori',
        description: 'imagetypesojori — libellés + rentalAmenityIds (ID type image RU).',
        path: '/admin/Listing/Image-Types',
        target: 'legacy',
        legacyTabHint: 'Onglet sojori_image_types',
        tags: ['Sojori', 'photos'],
        apiHint: 'image-types-sojori',
        database: 'srv-listing',
      },
      {
        id: 'image-types-ru',
        label: 'Types images RU',
        description: 'imagetypes — sync Pull_ListImageTypes_RQ.',
        path: '/admin/Listing/Image-Types',
        target: 'legacy',
        legacyTabHint: 'Onglet image_types',
        tags: ['RU', 'photos'],
        apiHint: 'syncListImageTypes',
        database: 'srv-listing',
      },
      {
        id: 'image-types-order',
        label: 'Ordre types images',
        description: 'Priorité catégories photo dans la galerie listing.',
        path: '/admin/Listing/Image-Types',
        target: 'legacy',
        legacyTabHint: 'Onglet image_types_order',
        tags: ['Sojori', 'UI'],
        database: 'srv-listing',
      },
    ],
  },
  {
    id: 'rooms-beds',
    label: 'Chambres, lits & property types',
    description: 'Composition RU, lits et PropertyTypeID.',
    items: [
      {
        id: 'room-type-config',
        label: 'Room types (composition RU)',
        description: 'Types de pièces / composition rooms Sojori.',
        path: '/admin/Listing/RoomTypeConfig',
        target: 'legacy',
        tags: ['RU', 'room'],
        apiHint: 'roomtypeconfigs',
        database: 'srv-listing',
      },
      {
        id: 'room-composite',
        label: 'Room composite',
        description: 'Matrices composition chambres RU.',
        path: '/admin/setting/roomComposite',
        target: 'legacy',
        tags: ['RU', 'room'],
        apiHint: 'compositionrooms',
        database: 'srv-listing',
      },
      {
        id: 'bed-types',
        label: 'Types de lit',
        description: 'Catalogue bed types.',
        path: '/admin/Listing/Bed-Type',
        target: 'legacy',
        legacyTabHint: 'Onglet bed_type',
        tags: ['Sojori'],
        database: 'srv-listing',
      },
      {
        id: 'bed-mapping',
        label: 'Mapping lits RU',
        description: 'Bed amenities RU ↔ Sojori.',
        path: '/admin/Listing/Bed-Type',
        target: 'legacy',
        legacyTabHint: 'Onglet bed_mapping',
        tags: ['RU'],
        apiHint: 'amenitiesbeds',
        database: 'srv-listing',
      },
      {
        id: 'property-types',
        label: 'Property types RU',
        description: 'PropertyTypeID RU ↔ type Sojori.',
        path: '/admin/Listing/Bed-Type',
        target: 'legacy',
        legacyTabHint: 'Onglet property_type',
        tags: ['RU'],
        apiHint: 'propertytypes · resolve-ru-property-types',
        database: 'srv-listing',
      },
    ],
  },
  {
    id: 'listing-meta',
    label: 'Structure, accès & frais RU',
    description: 'Référentiels listing utilisés à la publication RU.',
    items: [
      {
        id: 'listing-structure',
        label: 'Structure listing',
        description: 'Champs requis / optionnels par onglet formulaire.',
        path: '/admin/Listing/structure',
        target: 'legacy',
        tags: ['Sojori', 'formulaire'],
        database: 'srv-listing',
      },
      {
        id: 'standard-sojori',
        label: 'Standard Sojori',
        description: 'Standards qualité par ville (listing).',
        path: '/admin/Listing/StandardSojori',
        target: 'legacy',
        tags: ['Sojori'],
        database: 'srv-listing',
      },
      {
        id: 'access-types',
        label: 'Types d’accès',
        description: 'Modes d’accès logement sur le listing.',
        path: '/admin/Listing/access-type',
        target: 'legacy',
        database: 'srv-listing',
      },
      {
        id: 'tax-fees',
        label: 'Taxes & fees RU',
        description: 'Types tax/fee Rental United.',
        path: '/admin/Listing/tax-fees-config',
        target: 'legacy',
        tags: ['RU'],
        apiHint: 'taxandfees',
        database: 'srv-listing',
      },
      {
        id: 'additional-fees',
        label: 'Additional fee discriminators',
        description: 'Discriminateurs frais additionnels RU.',
        path: '/admin/Listing/additional-fee-discriminator-config',
        target: 'legacy',
        tags: ['RU'],
        database: 'srv-listing',
      },
      {
        id: 'payment-deposit',
        label: 'Payment methods & deposits',
        description: 'Catalogues paymentMethods / depositTypes (sync RU, résolus à l’import).',
        path: '/admin/Listing/amenityConfig',
        target: 'legacy',
        legacyTabHint: 'Pas d’écran dédié legacy — collections paymentmethods, deposittypes',
        tags: ['RU', 'import'],
        apiHint: 'payment-methods · deposit-types',
        database: 'srv-listing',
      },
    ],
  },
  {
    id: 'channels-ru',
    label: 'Canaux & XML RU',
    description: 'Liaisons OTA et dictionnaires champs RU pour listings.',
    items: [
      {
        id: 'channex-mapping',
        label: 'Channex mapping',
        description: 'Listing Sojori ↔ property Channex.',
        path: '/admin/Listing/Channex-Mapping',
        target: 'legacy',
        tags: ['Channex', 'OTA'],
        database: 'srv-listing',
      },
      {
        id: 'ru-field-mapping',
        label: 'Mapping champs RU (XML)',
        description: 'Valeurs Push/Pull RU (pays, langues, champs propriété).',
        path: '/admin/channels?tab=Mapping&mapSub=fields',
        target: 'orchestrator',
        tags: ['RU', 'XML'],
        apiHint: 'ChannelRuFieldMapping',
        database: 'srv-channels',
      },
    ],
  },
];
