/** Mapping nav id → pathname (react-router). Source unique avec navConfig. */
export const NAV_TO_ROUTE: Record<string, string> = {
  // Pilotage
  dashboard: '/dashboard',
  analytics: '/analytics',
  reports: '/reports',

  // Opérations
  reservations: '/reservations',
  'reservations/list': '/reservations',
  'reservations/planning': '/reservations/planning',
  payments: '/paiements',
  tasks: '/tasks',
  'tasks/list': '/tasks',
  'tasks/planning': '/tasks/planning',
  'tasks/kanban': '/tasks/kanban',
  'tasks/team': '/tasks/team',
  calendar: '/calendar',

  // Orchestration (routes réelles fulltask)
  orchestration: '/tasks/plans',
  'orch/plans': '/tasks/plans',
  'orch/ops': '/tasks/ops',
  'orch/workflows': '/tasks/orchestration-config',
  'orchestration/plans': '/tasks/plans',
  'orchestration/config': '/tasks/orchestration-config',
  'orchestration/whatsapp-messages': '/tasks/orchestration-config?tab=config',
  orchestrator: '/tasks/plans',
  'tasks/plans': '/tasks/plans',
  'tasks/orchestration-config': '/tasks/orchestration-config',
  'tasks/whatsapp-messages': '/tasks/orchestration-config?tab=config',
  'tasks/orchestration': '/tasks/plans',

  // Catalogue & revenue
  listings: '/listings',
  'listings/list': '/listings',
  'listings/mapping': '/listings/mapping',
  'listings/config': '/listings/orchestration-model',
  'listings/orchestration-model': '/listings/orchestration-model',
  'listing-orchestration': '/listings/orchestration-model',
  'listing-orchestration-v3': '/listings/orchestration-model',
  pricing: '/dynamic-pricing/portefeuille',
  'pricing/portfolio': '/dynamic-pricing/portefeuille',
  'pricing/audit': '/dynamic-pricing/audit',
  'dynamic-pricing/portefeuille': '/dynamic-pricing/portefeuille',
  'dynamic-pricing/audit': '/dynamic-pricing/audit',
  channels: '/catalogue/channels',
  'admin/channels': '/channels?tab=Business&biz=api&api=m',
  'admin/channels/business': '/admin/channels?tab=Business&biz=api&api=m',
  'admin/channels/debug': '/admin/channels?tab=Debug&type=pull',
  'admin/channels/summary': '/admin/channels?tab=Sum',
  'admin/ChannelManager/channel-manager': '/admin/ChannelManager?tab=channel-manager',
  'admin/ChannelManager/distribution': '/admin/ChannelManager?tab=distribution',

  // Relation client
  comms: '/communications',
  'comms/inbox': '/communications',
  'comms/guests': '/communications?tab=whatsapp',
  'comms/staff': '/communications?tab=staff',
  'comms/ota': '/communications?tab=ota',
  'comms/leads': '/communications?tab=leads',
  'comms/reviews': '/communications?tab=reviews',
  chatbot: '/chatbot/whitelist',
  'chatbot/whitelist': '/chatbot/whitelist',
  'chatbot/listing': '/chatbot/listing',
  crm: '/crm',
  'crm/clients': '/clients',
  'crm/requests': '/crm?tab=requests',
  'crm/leads': '/crm?tab=leads',
  'crm/support': '/crm?tab=support',
  'crm/onboarding': '/crm?tab=onboarding',
  'crm/reviews': '/reviews',
  clients: '/clients',
  requests: '/crm?tab=requests',
  reviews: '/reviews',

  // Équipe
  staff: '/tasks/team',
  'my-tasks': '/tasks',
  'my-sched': '/tasks/planning',
  'admin/equipe/staff': '/tasks/team',

  // Finances (pages dédiées à créer — placeholder)
  revenue: '/reports',
  statements: '/reports',

  // Monitor
  monitor: '/monitor?tab=Summary',
  'mon/summary': '/monitor?tab=Summary',
  'mon/logs': '/monitor?tab=Logs',
  'mon/metrics': '/monitor?tab=Metrics',
  'mon/rabbit': '/monitor?tab=RabbitMQ',
  'mon/wa': '/monitor?tab=WhatsApp',
  'mon/ai': '/monitor?tab=AI',
  'mon/infra': '/monitor?tab=Infrastructure',
  'mon/res-sync': '/monitor?tab=ReservationSync',
  'admin/monitor': '/monitor?tab=Summary',
  'admin/monitor/summary': '/monitor?tab=Summary',
  'admin/monitor/logs': '/monitor?tab=Logs',
  'admin/monitor/metrics': '/monitor?tab=Metrics',
  'admin/monitor/rabbitmq': '/monitor?tab=RabbitMQ',
  'admin/monitor/whatsapp': '/monitor?tab=WhatsApp',
  'admin/monitor/ai': '/monitor?tab=AI',
  'admin/monitor/infrastructure': '/monitor?tab=Infrastructure',
  'admin/monitor/reservation-sync': '/monitor?tab=ReservationSync',
  'admin/sojori-logs': '/admin/sojori-logs',

  // Administration
  'admin/pms': '/admin/equipe/owners?tab=list',
  'admin/mapping': '/admin/mapping',
  'admin/roles': '/admin/equipe?tab=worker',
  'admin/settings': '/admin/settings?tab=host-profile',
  'admin/equipe/owners': '/admin/equipe/owners?tab=list',
  'admin/equipe/roles': '/admin/equipe?tab=worker',
  'admin/equipe/groups': '/admin/equipe?tab=groups',
  'admin/settings/template': '/admin/settings?tab=template',
  'admin/settings/host-profile': '/admin/settings?tab=host-profile',
  'admin/settings/admin-config': '/admin/settings?tab=admin-config',
  'admin/setting/currency': '/admin/setting/currency',

  // Temp — pages legacy / placement à décider
  'temp/pricing-calendar': '/pricing',
  'temp/reservations-planning': '/reservations/planning',
  'temp/orch-rules': '/tasks/orchestration-config',
  'temp/sojori-logs': '/admin/sojori-logs',
  'temp/channel-distribution': '/admin/ChannelManager?tab=distribution',
  'temp/settings-template': '/admin/settings?tab=template',
  'temp/settings-currency': '/admin/setting/currency',
  'temp/settings-admin-config': '/admin/settings?tab=admin-config',
  'temp/equipe-groups': '/admin/equipe?tab=groups',
  'temp/tasks-team-legacy': '/tasks/team-legacy',
  'temp/booking-clients': '/temp/booking-clients',
};
